In [209]:
import pandas as pd
import numpy as np
import nltk
import re
import string

In [210]:
dataset = pd.read_csv(r"C:\Users\Shivam Jong Suk\Desktop\q1 data\spam.csv")

In [211]:
dataset.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [212]:
dataset = dataset.iloc[::,0:2:]

In [213]:
dataset.columns = ['type','message']

In [214]:
dataset

type                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will �_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [215]:
print(dataset['type'].isnull().sum())
print(dataset['message'].isnull().sum())

0
0


In [216]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [217]:
def rem_punc(text):
    nopunc = "".join([char  for char in text if char not in string.punctuation])
    return nopunc
dataset['message_nopunc'] = dataset['message'].apply(lambda x : rem_punc(x))

In [218]:
dataset

type                                            message  \
0      ham  Go until jurong point, crazy.. Available only ...   
1      ham                      Ok lar... Joking wif u oni...   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...   
3      ham  U dun say so early hor... U c already then say...   
4      ham  Nah I don't think he goes to usf, he lives aro...   
...    ...                                                ...   
5567  spam  This is the 2nd time we have tried 2 contact u...   
5568   ham              Will �_ b going to esplanade fr home?   
5569   ham  Pity, * was in mood for that. So...any other s...   
5570   ham  The guy did some bitching but I acted like i'd...   
5571   ham                         Rofl. Its true to its name   

                                         message_nopunc  
0     Go until jurong point crazy Available only in ...  
1                               Ok lar Joking wif u oni  
2     Free entry in 2 a wkly comp to win FA Cup fina...  
3           U dun say so early hor U c already then say  
4     Nah I dont think he goes to usf he lives aroun...  
...                                                 ...  
5567  This is the 2nd time we have tried 2 contact u...  
5568                Will � b going to esplanade fr home  
5569  Pity  was in mood for that Soany other suggest...  
5570  The guy did some bitching but I acted like id ...  
5571                          Rofl Its true to its name  

[5572 rows x 3 columns]

In [219]:
def token(text):
    tok = re.split('\W',text)
    return tok
dataset['message_tok'] = dataset['message_nopunc'].apply(lambda x: token(x.lower()))

In [220]:
dataset

type                                            message  \
0      ham  Go until jurong point, crazy.. Available only ...   
1      ham                      Ok lar... Joking wif u oni...   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...   
3      ham  U dun say so early hor... U c already then say...   
4      ham  Nah I don't think he goes to usf, he lives aro...   
...    ...                                                ...   
5567  spam  This is the 2nd time we have tried 2 contact u...   
5568   ham              Will �_ b going to esplanade fr home?   
5569   ham  Pity, * was in mood for that. So...any other s...   
5570   ham  The guy did some bitching but I acted like i'd...   
5571   ham                         Rofl. Its true to its name   

                                         message_nopunc  \
0     Go until jurong point crazy Available only in ...   
1                               Ok lar Joking wif u oni   
2     Free entry in 2 a wkly comp to win FA Cup fina...   
3           U dun say so early hor U c already then say   
4     Nah I dont think he goes to usf he lives aroun...   
...                                                 ...   
5567  This is the 2nd time we have tried 2 contact u...   
5568                Will � b going to esplanade fr home   
5569  Pity  was in mood for that Soany other suggest...   
5570  The guy did some bitching but I acted like id ...   
5571                          Rofl Its true to its name   

                                            message_tok  
0     [go, until, jurong, point, crazy, available, o...  
1                        [ok, lar, joking, wif, u, oni]  
2     [free, entry, in, 2, a, wkly, comp, to, win, f...  
3     [u, dun, say, so, early, hor, u, c, already, t...  
4     [nah, i, dont, think, he, goes, to, usf, he, l...  
...                                                 ...  
5567  [this, is, the, 2nd, time, we, have, tried, 2,...  
5568      [will, , , b, going, to, esplanade, fr, home]  
5569  [pity, , was, in, mood, for, that, soany, othe...  
5570  [the, guy, did, some, bitching, but, i, acted,...  
5571                   [rofl, its, true, to, its, name]  

[5572 rows x 4 columns]

In [221]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to C:\Users\Shivam Jong
[nltk_data]     Suk\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [222]:
stopwords = nltk.corpus.stopwords.words('english')
print(stopwords)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [223]:
def rem_sw(text):
    rem_s = [cha for cha in text if cha not in stopwords]
    return rem_s
dataset['message_stp'] = dataset['message_tok'].apply(lambda x: rem_sw(x))

In [224]:
dataset

type                                            message  \
0      ham  Go until jurong point, crazy.. Available only ...   
1      ham                      Ok lar... Joking wif u oni...   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...   
3      ham  U dun say so early hor... U c already then say...   
4      ham  Nah I don't think he goes to usf, he lives aro...   
...    ...                                                ...   
5567  spam  This is the 2nd time we have tried 2 contact u...   
5568   ham              Will �_ b going to esplanade fr home?   
5569   ham  Pity, * was in mood for that. So...any other s...   
5570   ham  The guy did some bitching but I acted like i'd...   
5571   ham                         Rofl. Its true to its name   

                                         message_nopunc  \
0     Go until jurong point crazy Available only in ...   
1                               Ok lar Joking wif u oni   
2     Free entry in 2 a wkly comp to win FA Cup fina...   
3           U dun say so early hor U c already then say   
4     Nah I dont think he goes to usf he lives aroun...   
...                                                 ...   
5567  This is the 2nd time we have tried 2 contact u...   
5568                Will � b going to esplanade fr home   
5569  Pity  was in mood for that Soany other suggest...   
5570  The guy did some bitching but I acted like id ...   
5571                          Rofl Its true to its name   

                                            message_tok  \
0     [go, until, jurong, point, crazy, available, o...   
1                        [ok, lar, joking, wif, u, oni]   
2     [free, entry, in, 2, a, wkly, comp, to, win, f...   
3     [u, dun, say, so, early, hor, u, c, already, t...   
4     [nah, i, dont, think, he, goes, to, usf, he, l...   
...                                                 ...   
5567  [this, is, the, 2nd, time, we, have, tried, 2,...   
5568      [will, , , b, going, to, esplanade, fr, home]   
5569  [pity, , was, in, mood, for, that, soany, othe...   
5570  [the, guy, did, some, bitching, but, i, acted,...   
5571                   [rofl, its, true, to, its, name]   

                                            message_stp  
0     [go, jurong, point, crazy, available, bugis, n...  
1                        [ok, lar, joking, wif, u, oni]  
2     [free, entry, 2, wkly, comp, win, fa, cup, fin...  
3         [u, dun, say, early, hor, u, c, already, say]  
4     [nah, dont, think, goes, usf, lives, around, t...  
...                                                 ...  
5567  [2nd, time, tried, 2, contact, u, u, , 750, po...  
5568                [, , b, going, esplanade, fr, home]  
5569                 [pity, , mood, soany, suggestions]  
5570  [guy, bitching, acted, like, id, interested, b...  
5571                                 [rofl, true, name]  

[5572 rows x 5 columns]

In [225]:
import nltk
wn = nltk.WordNetLemmatizer()
sn = nltk.PorterStemmer()

In [227]:

def lemmatizing(sptext):
    text = [wn.lemmatize(word) for word in sptext]
    return text
dataset['lemmatized'] = dataset['message_stp'].apply(lambda x: lemmatizing(x))


In [228]:
for i in range(0,5572):
    dataset['message'].loc[i] = ' '.join(dataset['lemmatized'].loc[i])
    

In [231]:
y = dataset['type']
y

0        ham
1        ham
2       spam
3        ham
4        ham
        ... 
5567    spam
5568     ham
5569     ham
5570     ham
5571     ham
Name: type, Length: 5572, dtype: object

In [232]:
dataset

type                                            message  \
0      ham  go jurong point crazy available bugis n great ...   
1      ham                            ok lar joking wif u oni   
2     spam  free entry 2 wkly comp win fa cup final tkts 2...   
3      ham                u dun say early hor u c already say   
4      ham           nah dont think go usf life around though   
...    ...                                                ...   
5567  spam  2nd time tried 2 contact u u  750 pound prize ...   
5568   ham                          b going esplanade fr home   
5569   ham                        pity  mood soany suggestion   
5570   ham  guy bitching acted like id interested buying s...   
5571   ham                                     rofl true name   

                                         message_nopunc  \
0     Go until jurong point crazy Available only in ...   
1                               Ok lar Joking wif u oni   
2     Free entry in 2 a wkly comp to win FA Cup fina...   
3           U dun say so early hor U c already then say   
4     Nah I dont think he goes to usf he lives aroun...   
...                                                 ...   
5567  This is the 2nd time we have tried 2 contact u...   
5568                Will � b going to esplanade fr home   
5569  Pity  was in mood for that Soany other suggest...   
5570  The guy did some bitching but I acted like id ...   
5571                          Rofl Its true to its name   

                                            message_tok  \
0     [go, until, jurong, point, crazy, available, o...   
1                        [ok, lar, joking, wif, u, oni]   
2     [free, entry, in, 2, a, wkly, comp, to, win, f...   
3     [u, dun, say, so, early, hor, u, c, already, t...   
4     [nah, i, dont, think, he, goes, to, usf, he, l...   
...                                                 ...   
5567  [this, is, the, 2nd, time, we, have, tried, 2,...   
5568      [will, , , b, going, to, esplanade, fr, home]   
5569  [pity, , was, in, mood, for, that, soany, othe...   
5570  [the, guy, did, some, bitching, but, i, acted,...   
5571                   [rofl, its, true, to, its, name]   

                                            message_stp  \
0     [go, jurong, point, crazy, available, bugis, n...   
1                        [ok, lar, joking, wif, u, oni]   
2     [free, entry, 2, wkly, comp, win, fa, cup, fin...   
3         [u, dun, say, early, hor, u, c, already, say]   
4     [nah, dont, think, goes, usf, lives, around, t...   
...                                                 ...   
5567  [2nd, time, tried, 2, contact, u, u, , 750, po...   
5568                [, , b, going, esplanade, fr, home]   
5569                 [pity, , mood, soany, suggestions]   
5570  [guy, bitching, acted, like, id, interested, b...   
5571                                 [rofl, true, name]   

                                             lemmatized  
0     [go, jurong, point, crazy, available, bugis, n...  
1                        [ok, lar, joking, wif, u, oni]  
2     [free, entry, 2, wkly, comp, win, fa, cup, fin...  
3         [u, dun, say, early, hor, u, c, already, say]  
4     [nah, dont, think, go, usf, life, around, though]  
...                                                 ...  
5567  [2nd, time, tried, 2, contact, u, u, , 750, po...  
5568                [, , b, going, esplanade, fr, home]  
5569                  [pity, , mood, soany, suggestion]  
5570  [guy, bitching, acted, like, id, interested, b...  
5571                                 [rofl, true, name]  

[5572 rows x 6 columns]

In [233]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect  = CountVectorizer()
x_count = count_vect.fit_transform(dataset['message'])
print(x_count.shape)
print(count_vect.get_feature_names())
print(x_count)

(5572, 8779)
['008704050406', '0089my', '0121', '01223585236', '01223585334', '0125698789', '02', '020603', '0207', '02070836089', '02072069400', '02073162414', '02085076972', '020903', '021', '050703', '0578', '06', '060505', '061104', '07008009200', '07046744435', '07090201529', '07090298926', '07099833605', '071104', '07123456789', '0721072', '07732584351', '07734396839', '07742676969', '07753741225', '0776xxxxxxx', '07786200117', '077xxx', '078', '07801543489', '07808', '07808247860', '07808726822', '07815296484', '07821230901', '0784987', '0789xxxxxxx', '0794674629107880867867', '0796xxxxxx', '07973788240', '07xxxxxxxxx', '0800', '08000407165', '08000776320', '08000839402', '08000930705', '08000938767', '08001950382', '08002888812', '08002986030', '08002986906', '08002988890', '08006344447', '0808', '08081263000', '08081560665', '0825', '0844', '08448350055', '08448714184', '0845', '08450542832', '08452810071', '08452810073', '08452810075over18s', '0870', '08700621170150p', '08701

In [234]:
dataset = pd.DataFrame(x_count.toarray())

In [235]:
dataset.head()

0     1     2     3     4     5     6     7     8     9     ...  8769  \
0     0     0     0     0     0     0     0     0     0     0  ...     0   
1     0     0     0     0     0     0     0     0     0     0  ...     0   
2     0     0     0     0     0     0     0     0     0     0  ...     0   
3     0     0     0     0     0     0     0     0     0     0  ...     0   
4     0     0     0     0     0     0     0     0     0     0  ...     0   

   8770  8771  8772  8773  8774  8775  8776  8777  8778  
0     0     0     0     0     0     0     0     0     0  
1     0     0     0     0     0     0     0     0     0  
2     0     0     0     0     0     0     0     0     0  
3     0     0     0     0     0     0     0     0     0  
4     0     0     0     0     0     0     0     0     0  

[5 rows x 8779 columns]

In [237]:
x = x_count.toarray()

In [238]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
y = labelencoder.fit_transform(y)
y

array([0, 0, 1, ..., 0, 0, 0])

In [239]:
print(x.shape)
print(y.shape)

(5572, 8779)
(5572,)


In [240]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 0)

In [241]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(4457, 8779)
(4457,)
(1115, 8779)
(1115,)


In [281]:
#from sklearn.naive_bayes import GaussianNB
#classifier = GaussianNB()
#classifier.fit(x_train,y_train)
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=3)
classifier.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [282]:
y_pred = classifier.predict(x_test)

In [283]:
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [284]:
y_test

array([0, 0, 0, ..., 0, 0, 0])

In [285]:
classifier.score(x_test,y_test)

0.9183856502242153

In [286]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)

In [287]:
cm

array([[949,   0],
       [ 91,  75]], dtype=int64)

In [288]:
count = 0
for x in y:
    if(x==0):
        count+=1
count

4825